### ISSUE TITLE
Heroku Deployments Failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#3849]
Probably related/caused by https://github.com/badges/shields/pull/3835. Heroku deployments being broken will make reviewing PRs challenging so adding the blocker label to this.

Seems like `anafanafo`, one of the `gh-badges` dependencies is missing:
```
internal/modules/cjs/loader.js:716
    throw err;
    ^
Error: Cannot find module 'anafanafo'
Require stack:
- /tmp/build_f02b8626b9622e3c1ef9c7a03676378c/gh-badges/lib/make-badge.js
- /tmp/build_f02b8626b9622e3c1ef9c7a03676378c/core/base-service/base-non-memory-caching.js
- /tmp/build_f02b8626b9622e3c1ef9c7a03676378c/core/base-service/index.js
- /tmp/build_f02b8626b9622e3c1ef9c7a03676378c/services/index.js
- /tmp/build_f02b8626b9622e3c1ef9c7a03676378c/services/amo/amo-base.js
- /tmp/build_f02b8626b9622e3c1ef9c7a03676378c/services/amo/amo-downloads.service.js
- /tmp/build_f02b8626b9622e3c1ef9c7a03676378c/core/base-service/loader.js
- /tmp/build_f02b8626b9622e3c1ef9c7a03676378c/scripts/export-service-definitions-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/tmp/build_f02b8626b9622e3c1ef9c7a03676378c/gh-badges/lib/make-badge.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/build_f02b8626b9622e3c1ef9c7a03676378c/gh-badges/lib/make-badge.js',
    '/tmp/build_f02b8626b9622e3c1ef9c7a03676378c/core/base-service/base-non-memory-caching.js',
    '/tmp/build_f02b8626b9622e3c1ef9c7a03676378c/core/base-service/index.js',
    '/tmp/build_f02b8626b9622e3c1ef9c7a03676378c/services/index.js',
    '/tmp/build_f02b8626b9622e3c1ef9c7a03676378c/services/amo/amo-base.js',
    '/tmp/build_f02b8626b9622e3c1ef9c7a03676378c/services/amo/amo-downloads.service.js',
    '/tmp/build_f02b8626b9622e3c1ef9c7a03676378c/core/base-service/loader.js',
    '/tmp/build_f02b8626b9622e3c1ef9c7a03676378c/scripts/export-service-definitions-cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shields.io@0.0.0 heroku-postbuild: `run-s --silent build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shields.io@0.0.0 heroku-postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.LsYUU/_logs/2019-08-11T17_35_35_772Z-debug.log
```

**Comment by paulmelnikow** [comment]
I haven't had a chance to do it, though what I'd suggest is that we revert the offending commit and then re-attempt the `npm install` on a clean tree (maybe not on Windows?) and see if that produces a better lockfile.

**Comment by calebcartwright** [comment]
In my local env I changed the `gh-badges` dependency from `"gh-badges": "file:gh-badges",` to `"gh-badges": "file:./gh-badges",` and it's working for me

**Comment by calebcartwright** [comment]
also worked as is from Linux so i'll just roll with that fix. windows 🤷‍♂

**Comment by calebcartwright** [comment]
Actually it looks like dependabot and/or Chris already fixed this so I'm going to close it out
